// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1YIWZhz_G6O0avHzElMtzbPnK_QSzMtU',
    appId: '1:443808602359:web:c480169431f2fdd5665bf2',
    messagingSenderId: '443808602359',
    projectId: 'hearify-1c669',
    authDomain: 'hearify-1c669.firebaseapp.com',
    storageBucket: 'hearify-1c669.firebasestorage.app',
    measurementId: 'G-XW94128WES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnAoOBadCoOh7pdz7X91hcf2k72Mr-1hQ',
    appId: '1:443808602359:android:58171c42b10a3262665bf2',
    messagingSenderId: '443808602359',
    projectId: 'hearify-1c669',
    storageBucket: 'hearify-1c669.firebasestorage.app',
  );

  // Values mirror ios/Runner/GoogleService-Info.plist for the
  // `com.hearify.hearify` bundle id.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2dL6bBUBldfLlabRMZ72kont_J5msTX8',
    appId: '1:443808602359:ios:5124702c744b0e30665bf2',
    messagingSenderId: '443808602359',
    projectId: 'hearify-1c669',
    storageBucket: 'hearify-1c669.firebasestorage.app',
    iosBundleId: 'com.hearify.hearify',
  );
}
